### ISSUE TITLE
Logo

### ISSUE THREAD

**Issue by paulstatezny** [mattludwigs/kepler#1]
I think this project needs a killer 80's style logo.

**Comment by mattludwigs** [comment]
I agree

**Comment by mattludwigs** [comment]
@paulstatezny thoughts?
![screen shot 2018-02-13 at 10 16 34 am](https://user-images.githubusercontent.com/6612164/36163592-051f711e-10a7-11e8-8236-a8d483ffd09e.png)

**Comment by paulstatezny** [comment]
![screen shot 2018-02-13 at 10 16 50 am](https://user-images.githubusercontent.com/4662353/36163597-0c1be0e2-10a7-11e8-8415-5454820be145.png)

**Comment by paulstatezny** [comment]
I think we need a spike for this.

**Comment by mattludwigs** [comment]
Done!
